version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api
    environment:
      MYSQL_DATABASE: 'vapor'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: bash
  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: password
    ports:
        - 3306:3306
    volumes:
        - ./db:/var/lib/mysql